version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: idiogo_mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sOdifn3ijnvsd8!